### PR TITLE
Added Travis Support

### LINKED ISSUE #6: Setup travis

### PR DESCRIPTION
**Pull request by ConradoMateu**
Configured project and .travis.yml in order to set up travis.
Here is the last build executed correctly: https://travis-ci.org/ConradoMateu/bow

close #6

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @ConradoMateu, thanks for the contribution! 

We've renamed the project to 'Bow' and change the structure of the project to make it compatible with SPM, cocoapods and carthage, so there are a few changes needed now:

* The project is now build using Carthage, you can see the steps to run in the new Readme [https://github.com/arrow-kt/bow/pull/11](PR). So you now will have to execute `carthage bootstrap` before compiling the project.
* The new target to build is not called `CategoryCore` anymore. It's called `Bow`
* You don't need to expose a new test target to use xcodebuild to test it. You can call `xcodebuild test ... ` and as this target has testing enabled, it will work and execute the tests :)
* AFAIK xcpretty is already installed in the xcode images from travis. [https://blog.travis-ci.com/2017-12-06-xcode-92-has-landed](link).

The PR will be ready to merge after addressing these things. If you have some questions or problem I can help you :)

**Comment by victorg1991** [comment]
@raulraja I think we should enable travis for this repo too

**Comment by ConradoMateu** [comment]
@victorg1991 I will correct this issues as soon as possible 🙌

I'll let you know if I'm stuck.

Thank you!

**Comment by ConradoMateu** [comment]
I have just configured Carthage in the project following your instructions.
I can configure travis to run in a specific branch.Now it runs with every one.
:)

**Comment by victorg1991** [comment]
Awesome 👏 
Thanks!!

**Pull request merged**
